name: Build and Package
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyperclip pynput pyinstaller
    - name: Run package script
      run: python package.py
    - name: List contents of dist directory
      run: ls -lh dist
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: skyblock_ah_flipper
        path: dist/*
        if-no-files-found: error
