name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyperclip pynput pyinstaller

    - name: Run package script
      run: python package.py

    - name: Move executable to root directory
      shell: pwsh
      run: |
        Move-Item -Path "dist\*.exe" -Destination "skyblock_ah_flipper.exe" -Force
        if (-not (Test-Path "skyblock_ah_flipper.exe")) {
          Write-Error "Executable not found"
          exit 1
        }

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add skyblock_ah_flipper.exe
        git commit -m "Update executable" -a || echo "No changes to commit"
        git push

    - name: Upload artifact (as backup)
      uses: actions/upload-artifact@v3
      with:
        name: skyblock_ah_flipper
        path: skyblock_ah_flipper.exe
        if-no-files-found: error